/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Cart,
  Coupon,
} from '../models/index';
import {
    CartFromJSON,
    CartToJSON,
    CouponFromJSON,
    CouponToJSON,
} from '../models/index';

export interface ApplyCouponRequest {
    apply: string;
    code: string;
    orderValue: number;
    authorization: string;
}

export interface CreateCouponRequest {
    coupon: Coupon;
}

export interface DeleteCouponRequest {
    id: number;
}

/**
 * 
 */
export class CouponControllerApi extends runtime.BaseAPI {

    /**
     */
    async applyCouponRaw(requestParameters: ApplyCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Cart>> {
        if (requestParameters['apply'] == null) {
            throw new runtime.RequiredError(
                'apply',
                'Required parameter "apply" was null or undefined when calling applyCoupon().'
            );
        }

        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling applyCoupon().'
            );
        }

        if (requestParameters['orderValue'] == null) {
            throw new runtime.RequiredError(
                'orderValue',
                'Required parameter "orderValue" was null or undefined when calling applyCoupon().'
            );
        }

        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling applyCoupon().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apply'] != null) {
            queryParameters['apply'] = requestParameters['apply'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['orderValue'] != null) {
            queryParameters['orderValue'] = requestParameters['orderValue'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['Authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/coupons/apply`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartFromJSON(jsonValue));
    }

    /**
     */
    async applyCoupon(requestParameters: ApplyCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Cart> {
        const response = await this.applyCouponRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createCouponRaw(requestParameters: CreateCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Coupon>> {
        if (requestParameters['coupon'] == null) {
            throw new runtime.RequiredError(
                'coupon',
                'Required parameter "coupon" was null or undefined when calling createCoupon().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/coupons/admin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CouponToJSON(requestParameters['coupon']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CouponFromJSON(jsonValue));
    }

    /**
     */
    async createCoupon(requestParameters: CreateCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Coupon> {
        const response = await this.createCouponRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteCouponRaw(requestParameters: DeleteCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCoupon().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/coupons/admin/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async deleteCoupon(requestParameters: DeleteCouponRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteCouponRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllCouponsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Coupon>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/coupons/admin`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CouponFromJSON));
    }

    /**
     */
    async getAllCoupons(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Coupon>> {
        const response = await this.getAllCouponsRaw(initOverrides);
        return await response.value();
    }

}
