/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCartItemRequestDto
 */
export interface AddCartItemRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AddCartItemRequestDto
     */
    size?: string;
    /**
     * 
     * @type {number}
     * @memberof AddCartItemRequestDto
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof AddCartItemRequestDto
     */
    productId?: number;
}

/**
 * Check if a given object implements the AddCartItemRequestDto interface.
 */
export function instanceOfAddCartItemRequestDto(value: object): value is AddCartItemRequestDto {
    return true;
}

export function AddCartItemRequestDtoFromJSON(json: any): AddCartItemRequestDto {
    return AddCartItemRequestDtoFromJSONTyped(json, false);
}

export function AddCartItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCartItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'size': json['size'] == null ? undefined : json['size'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'productId': json['productId'] == null ? undefined : json['productId'],
    };
}

export function AddCartItemRequestDtoToJSON(json: any): AddCartItemRequestDto {
    return AddCartItemRequestDtoToJSONTyped(json, false);
}

export function AddCartItemRequestDtoToJSONTyped(value?: AddCartItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size': value['size'],
        'quantity': value['quantity'],
        'productId': value['productId'],
    };
}

