/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankDetails
 */
export interface BankDetails {
    /**
     * 
     * @type {string}
     * @memberof BankDetails
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof BankDetails
     */
    accountHolderName?: string;
    /**
     * 
     * @type {string}
     * @memberof BankDetails
     */
    ifscCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BankDetails
     */
    bankName?: string;
}

/**
 * Check if a given object implements the BankDetails interface.
 */
export function instanceOfBankDetails(value: object): value is BankDetails {
    return true;
}

export function BankDetailsFromJSON(json: any): BankDetails {
    return BankDetailsFromJSONTyped(json, false);
}

export function BankDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'accountHolderName': json['accountHolderName'] == null ? undefined : json['accountHolderName'],
        'ifscCode': json['ifscCode'] == null ? undefined : json['ifscCode'],
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
    };
}

export function BankDetailsToJSON(json: any): BankDetails {
    return BankDetailsToJSONTyped(json, false);
}

export function BankDetailsToJSONTyped(value?: BankDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNumber': value['accountNumber'],
        'accountHolderName': value['accountHolderName'],
        'ifscCode': value['ifscCode'],
        'bankName': value['bankName'],
    };
}

