/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductRequestDto
 */
export interface CreateProductRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequestDto
     */
    mrpPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProductRequestDto
     */
    sellingPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    color?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateProductRequestDto
     */
    images?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    categoryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    categoryCode2?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    categoryCode3?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductRequestDto
     */
    size?: string;
}

/**
 * Check if a given object implements the CreateProductRequestDto interface.
 */
export function instanceOfCreateProductRequestDto(value: object): value is CreateProductRequestDto {
    return true;
}

export function CreateProductRequestDtoFromJSON(json: any): CreateProductRequestDto {
    return CreateProductRequestDtoFromJSONTyped(json, false);
}

export function CreateProductRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'mrpPrice': json['mrpPrice'] == null ? undefined : json['mrpPrice'],
        'sellingPrice': json['sellingPrice'] == null ? undefined : json['sellingPrice'],
        'color': json['color'] == null ? undefined : json['color'],
        'images': json['images'] == null ? undefined : json['images'],
        'categoryCode': json['categoryCode'] == null ? undefined : json['categoryCode'],
        'categoryCode2': json['categoryCode2'] == null ? undefined : json['categoryCode2'],
        'categoryCode3': json['categoryCode3'] == null ? undefined : json['categoryCode3'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function CreateProductRequestDtoToJSON(json: any): CreateProductRequestDto {
    return CreateProductRequestDtoToJSONTyped(json, false);
}

export function CreateProductRequestDtoToJSONTyped(value?: CreateProductRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'mrpPrice': value['mrpPrice'],
        'sellingPrice': value['sellingPrice'],
        'color': value['color'],
        'images': value['images'],
        'categoryCode': value['categoryCode'],
        'categoryCode2': value['categoryCode2'],
        'categoryCode3': value['categoryCode3'],
        'size': value['size'],
    };
}

