/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReviewRequest
 */
export interface CreateReviewRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReviewRequest
     */
    reviewText?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateReviewRequest
     */
    reviewRating?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateReviewRequest
     */
    productImages?: Array<string>;
}

/**
 * Check if a given object implements the CreateReviewRequest interface.
 */
export function instanceOfCreateReviewRequest(value: object): value is CreateReviewRequest {
    return true;
}

export function CreateReviewRequestFromJSON(json: any): CreateReviewRequest {
    return CreateReviewRequestFromJSONTyped(json, false);
}

export function CreateReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewText': json['reviewText'] == null ? undefined : json['reviewText'],
        'reviewRating': json['reviewRating'] == null ? undefined : json['reviewRating'],
        'productImages': json['productImages'] == null ? undefined : json['productImages'],
    };
}

export function CreateReviewRequestToJSON(json: any): CreateReviewRequest {
    return CreateReviewRequestToJSONTyped(json, false);
}

export function CreateReviewRequestToJSONTyped(value?: CreateReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reviewText': value['reviewText'],
        'reviewRating': value['reviewRating'],
        'productImages': value['productImages'],
    };
}

