/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Deal } from './Deal';
import {
    DealFromJSON,
    DealFromJSONTyped,
    DealToJSON,
    DealToJSONTyped,
} from './Deal';
import type { HomeCategory } from './HomeCategory';
import {
    HomeCategoryFromJSON,
    HomeCategoryFromJSONTyped,
    HomeCategoryToJSON,
    HomeCategoryToJSONTyped,
} from './HomeCategory';

/**
 * 
 * @export
 * @interface Home
 */
export interface Home {
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    grid?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    shopByCategories?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    electricCategories?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<HomeCategory>}
     * @memberof Home
     */
    dealCategories?: Array<HomeCategory>;
    /**
     * 
     * @type {Array<Deal>}
     * @memberof Home
     */
    deals?: Array<Deal>;
}

/**
 * Check if a given object implements the Home interface.
 */
export function instanceOfHome(value: object): value is Home {
    return true;
}

export function HomeFromJSON(json: any): Home {
    return HomeFromJSONTyped(json, false);
}

export function HomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Home {
    if (json == null) {
        return json;
    }
    return {
        
        'grid': json['grid'] == null ? undefined : ((json['grid'] as Array<any>).map(HomeCategoryFromJSON)),
        'shopByCategories': json['shopByCategories'] == null ? undefined : ((json['shopByCategories'] as Array<any>).map(HomeCategoryFromJSON)),
        'electricCategories': json['electricCategories'] == null ? undefined : ((json['electricCategories'] as Array<any>).map(HomeCategoryFromJSON)),
        'dealCategories': json['dealCategories'] == null ? undefined : ((json['dealCategories'] as Array<any>).map(HomeCategoryFromJSON)),
        'deals': json['deals'] == null ? undefined : ((json['deals'] as Array<any>).map(DealFromJSON)),
    };
}

export function HomeToJSON(json: any): Home {
    return HomeToJSONTyped(json, false);
}

export function HomeToJSONTyped(value?: Home | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grid': value['grid'] == null ? undefined : ((value['grid'] as Array<any>).map(HomeCategoryToJSON)),
        'shopByCategories': value['shopByCategories'] == null ? undefined : ((value['shopByCategories'] as Array<any>).map(HomeCategoryToJSON)),
        'electricCategories': value['electricCategories'] == null ? undefined : ((value['electricCategories'] as Array<any>).map(HomeCategoryToJSON)),
        'dealCategories': value['dealCategories'] == null ? undefined : ((value['dealCategories'] as Array<any>).map(HomeCategoryToJSON)),
        'deals': value['deals'] == null ? undefined : ((value['deals'] as Array<any>).map(DealToJSON)),
    };
}

