/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * 
     * @type {string}
     * @memberof LoginDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDto
     */
    otp?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDto
     */
    role?: LoginDtoRoleEnum;
}


/**
 * @export
 */
export const LoginDtoRoleEnum = {
    RoleAdmin: 'ROLE_ADMIN',
    RoleCustomer: 'ROLE_CUSTOMER',
    RoleSeller: 'ROLE_SELLER'
} as const;
export type LoginDtoRoleEnum = typeof LoginDtoRoleEnum[keyof typeof LoginDtoRoleEnum];


/**
 * Check if a given object implements the LoginDto interface.
 */
export function instanceOfLoginDto(value: object): value is LoginDto {
    return true;
}

export function LoginDtoFromJSON(json: any): LoginDto {
    return LoginDtoFromJSONTyped(json, false);
}

export function LoginDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'otp': json['otp'] == null ? undefined : json['otp'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function LoginDtoToJSON(json: any): LoginDto {
    return LoginDtoToJSONTyped(json, false);
}

export function LoginDtoToJSONTyped(value?: LoginDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'otp': value['otp'],
        'role': value['role'],
    };
}

