/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    razorpayPaymentLinkId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    razorpayPaymentReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    razorpayPaymentStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    razorpayPaymentIdZWSP?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    status?: PaymentDetailsStatusEnum;
}


/**
 * @export
 */
export const PaymentDetailsStatusEnum = {
    Pending: 'PENDING',
    Processing: 'PROCESSING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type PaymentDetailsStatusEnum = typeof PaymentDetailsStatusEnum[keyof typeof PaymentDetailsStatusEnum];


/**
 * Check if a given object implements the PaymentDetails interface.
 */
export function instanceOfPaymentDetails(value: object): value is PaymentDetails {
    return true;
}

export function PaymentDetailsFromJSON(json: any): PaymentDetails {
    return PaymentDetailsFromJSONTyped(json, false);
}

export function PaymentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'razorpayPaymentLinkId': json['razorpayPaymentLinkId'] == null ? undefined : json['razorpayPaymentLinkId'],
        'razorpayPaymentReferenceId': json['razorpayPaymentReferenceId'] == null ? undefined : json['razorpayPaymentReferenceId'],
        'razorpayPaymentStatus': json['razorpayPaymentStatus'] == null ? undefined : json['razorpayPaymentStatus'],
        'razorpayPaymentIdZWSP': json['razorpayPaymentIdZWSP'] == null ? undefined : json['razorpayPaymentIdZWSP'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentDetailsToJSON(json: any): PaymentDetails {
    return PaymentDetailsToJSONTyped(json, false);
}

export function PaymentDetailsToJSONTyped(value?: PaymentDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'razorpayPaymentLinkId': value['razorpayPaymentLinkId'],
        'razorpayPaymentReferenceId': value['razorpayPaymentReferenceId'],
        'razorpayPaymentStatus': value['razorpayPaymentStatus'],
        'razorpayPaymentIdZWSP': value['razorpayPaymentIdZWSP'],
        'status': value['status'],
    };
}

