/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentLinkResponseDto
 */
export interface PaymentLinkResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    paymentLinkUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkResponseDto
     */
    paymentLinkId?: string;
}

/**
 * Check if a given object implements the PaymentLinkResponseDto interface.
 */
export function instanceOfPaymentLinkResponseDto(value: object): value is PaymentLinkResponseDto {
    return true;
}

export function PaymentLinkResponseDtoFromJSON(json: any): PaymentLinkResponseDto {
    return PaymentLinkResponseDtoFromJSONTyped(json, false);
}

export function PaymentLinkResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentLinkResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentLinkUrl': json['payment_link_url'] == null ? undefined : json['payment_link_url'],
        'paymentLinkId': json['payment_link_id'] == null ? undefined : json['payment_link_id'],
    };
}

export function PaymentLinkResponseDtoToJSON(json: any): PaymentLinkResponseDto {
    return PaymentLinkResponseDtoToJSONTyped(json, false);
}

export function PaymentLinkResponseDtoToJSONTyped(value?: PaymentLinkResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_link_url': value['paymentLinkUrl'],
        'payment_link_id': value['paymentLinkId'],
    };
}

