/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    reviewText?: string;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    rating?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Review
     */
    productImages?: Array<string>;
    /**
     * 
     * @type {User}
     * @memberof Review
     */
    user?: User;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reviewText': json['reviewText'] == null ? undefined : json['reviewText'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'productImages': json['productImages'] == null ? undefined : json['productImages'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'reviewText': value['reviewText'],
        'rating': value['rating'],
        'productImages': value['productImages'],
        'user': UserToJSON(value['user']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

