/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendAuthOtpRequest
 */
export interface SendAuthOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof SendAuthOtpRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof SendAuthOtpRequest
     */
    otp?: string;
    /**
     * 
     * @type {string}
     * @memberof SendAuthOtpRequest
     */
    role?: SendAuthOtpRequestRoleEnum;
}


/**
 * @export
 */
export const SendAuthOtpRequestRoleEnum = {
    RoleAdmin: 'ROLE_ADMIN',
    RoleCustomer: 'ROLE_CUSTOMER',
    RoleSeller: 'ROLE_SELLER'
} as const;
export type SendAuthOtpRequestRoleEnum = typeof SendAuthOtpRequestRoleEnum[keyof typeof SendAuthOtpRequestRoleEnum];


/**
 * Check if a given object implements the SendAuthOtpRequest interface.
 */
export function instanceOfSendAuthOtpRequest(value: object): value is SendAuthOtpRequest {
    return true;
}

export function SendAuthOtpRequestFromJSON(json: any): SendAuthOtpRequest {
    return SendAuthOtpRequestFromJSONTyped(json, false);
}

export function SendAuthOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendAuthOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'otp': json['otp'] == null ? undefined : json['otp'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function SendAuthOtpRequestToJSON(json: any): SendAuthOtpRequest {
    return SendAuthOtpRequestToJSONTyped(json, false);
}

export function SendAuthOtpRequestToJSONTyped(value?: SendAuthOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'otp': value['otp'],
        'role': value['role'],
    };
}

