/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface UpdateProductRequestDto
 */
export interface UpdateProductRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequestDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequestDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequestDto
     */
    mrpPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequestDto
     */
    sellingPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequestDto
     */
    discountPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequestDto
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequestDto
     */
    color?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProductRequestDto
     */
    images?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UpdateProductRequestDto
     */
    numRatings?: number;
    /**
     * 
     * @type {Category}
     * @memberof UpdateProductRequestDto
     */
    category?: Category;
    /**
     * 
     * @type {string}
     * @memberof UpdateProductRequestDto
     */
    size?: string;
}

/**
 * Check if a given object implements the UpdateProductRequestDto interface.
 */
export function instanceOfUpdateProductRequestDto(value: object): value is UpdateProductRequestDto {
    return true;
}

export function UpdateProductRequestDtoFromJSON(json: any): UpdateProductRequestDto {
    return UpdateProductRequestDtoFromJSONTyped(json, false);
}

export function UpdateProductRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'mrpPrice': json['mrpPrice'] == null ? undefined : json['mrpPrice'],
        'sellingPrice': json['sellingPrice'] == null ? undefined : json['sellingPrice'],
        'discountPercent': json['discountPercent'] == null ? undefined : json['discountPercent'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'color': json['color'] == null ? undefined : json['color'],
        'images': json['images'] == null ? undefined : json['images'],
        'numRatings': json['numRatings'] == null ? undefined : json['numRatings'],
        'category': json['category'] == null ? undefined : CategoryFromJSON(json['category']),
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function UpdateProductRequestDtoToJSON(json: any): UpdateProductRequestDto {
    return UpdateProductRequestDtoToJSONTyped(json, false);
}

export function UpdateProductRequestDtoToJSONTyped(value?: UpdateProductRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'mrpPrice': value['mrpPrice'],
        'sellingPrice': value['sellingPrice'],
        'discountPercent': value['discountPercent'],
        'quantity': value['quantity'],
        'color': value['color'],
        'images': value['images'],
        'numRatings': value['numRatings'],
        'category': CategoryToJSON(value['category']),
        'size': value['size'],
    };
}

