/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCartItemRequestDto
 */
export interface UpdateCartItemRequestDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateCartItemRequestDto
     */
    quantity?: number;
}

/**
 * Check if a given object implements the UpdateCartItemRequestDto interface.
 */
export function instanceOfUpdateCartItemRequestDto(value: object): value is UpdateCartItemRequestDto {
    return true;
}

export function UpdateCartItemRequestDtoFromJSON(json: any): UpdateCartItemRequestDto {
    return UpdateCartItemRequestDtoFromJSONTyped(json, false);
}

export function UpdateCartItemRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCartItemRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function UpdateCartItemRequestDtoToJSON(json: any): UpdateCartItemRequestDto {
    return UpdateCartItemRequestDtoToJSONTyped(json, false);
}

export function UpdateCartItemRequestDtoToJSONTyped(value?: UpdateCartItemRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
    };
}

